language: node_js
node_js:
  - "0.12"
  - "iojs"
before_install:
  # Setup for installing LLVM
  - sudo apt-get update
  - sudo apt-get install python-software-properties
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
install:
  - sudo apt-get update
  # Install LLVM
  - sudo apt-get install -y llvm-3.5 llvm-3.5-dev
script: "npm run test"

