sudo: false

# Support for Node.js v4.x
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      # Support for LLVM
      - libstdc++6
      # Install LLVM
      - llvm-3.6
      - llvm-3.6-dev
      - llvm-3.6-runtime
      - libllvm3.6
      - libllvm3.6-dbg

language: node_js

node_js:
  - "stable"
  - "4.1.0"
  - "0.12"

install:
  - npm install

before_script:
  - export LD_LIBRARY_PATH=/usr/lib/llvm-3.6/lib:$LD_LIBRARY_PATH

script: "npm run test"
