language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "iojs-v1.0.4"
before_install:
  # - sudo apt-get update
  # - sudo apt-get install python-software-properties
  # Setup for installing LLVM
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main' >> /etc/apt/sources.list"
  - sudo sh -c "echo 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
install:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes libstdc++6
  # Install LLVM
  - sudo apt-get install -y llvm-3.6 llvm-3.6-dev llvm-3.6-runtime libllvm3.6 libllvm3.6-dbg
  - npm install
before_script:
  - export LD_LIBRARY_PATH=/usr/lib/llvm-3.6/lib:$LD_LIBRARY_PATH
script: "npm run test"

